void fragmentPixelLight(float3 color	: COLOR;
						float2 texCoord	: TEXCOORD0;
						float3 normal	: TEXCOORD1;
						float3 lightDir	: TEXCOORD2;
						float3 eyeDir	: TEXCOORD3;

						out float4 outColor : COLOR,

						uniform sampler2D decalMap,
						uniform sampler2D normalMap,)
{
	// per vertex light first

	// diffuse light
	float diffInt = dot(normal, lightDir);
	float3 decal = tex2D(decalMap, texCoord).xyz;

	float3 diffLight = diffInt * decal;

	outColor = float4(diffLight, 1);
}
