
//vertext output
struct Vertex_Output
{
	float4 position	: POSITION;
	float4 color	: COLOR;
	float2 texCoord	: TEXCOORD0;
};

//vertex shader
Vertex_Output VS_program(float4 position	: POSITION,
							float4 color	: COLOR,
							float2 texCoord : TEXCOORD0,

							uniform float4x4 modelViewProj)
{
	Vertex_Output OUT;

	OUT.position = mul(modelViewProj, position);
	OUT.color = color;
	OUT.texCoord = texCoord;

	return OUT;
}

